[global]
strict init = true
buffer min = 1024
buffer max = 2MB
file perms = 0644

[formats]
simple = "%d(%F %T.%ms) %-5V [%18.18f:%04L] %m%n"

[rules]
resource_manager.DEBUG    "/var/log/resource_manager.log"; simple
